name: Continuous Integration Workflow
on: [push]
jobs:
  build-and-test:
    name: Build and run tests
    runs-on: macos-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v1
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Download Importat file
        run: wget ${{ secrets.API_JSON }} -q -O app/src/main/res/raw/testagentcredentials.json 
      - name: Print contents in current directory
        run: ls -la app/src/main/res/raw/
      - name: Print contents in current directory
        run: cat app/src/main/res/raw/testagentcredentials.json
